version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=9dze554$$8jl89l_@5d1)b(84ebm07j6r=gs86%6z1*2uzsfu3f
      - DEBUG=1
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postfresql/data/

volumes:
  postgres_data: