# Generated by Django 3.0.5 on 2020-04-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('special_status', 'Can see all products')]},
        ),
    ]
